services:
  db:
    image: postgres:16
    container_name: MindSyncr-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: MindSyncr
    ports:
      - "5555:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d MindSyncr"]
      interval: 3s
      timeout: 5s
      retries: 10

  migrations:
    image: ghcr.io/kukymbr/goose-docker:3.24.2
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: host=db port=5432 user=postgres password=postgres dbname=MindSyncr sslmode=disable
    volumes:
      - ./backend/api-gateway/internal/db/migrations:/migrations
    restart: "no"

  redis:
    image: redis:7.4-alpine
    container_name: MindSyncr-redis
    ports:
    - "6379:6379"
    volumes:
    - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend:
    build:
      context: ./backend/api-gateway
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-development}
    depends_on:
      db:
        condition: service_healthy
      migrations:
        condition: service_completed_successfully
      redis:
        condition: service_healthy
    env_file:
    - ./backend/api-gateway/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/MindSyncr?sslmode=disable
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: rebuild
          path: ./backend/api-gateway/go.mod
        
        - action: rebuild
          path: ./backend/api-gateway/go.sum
        
        - action: rebuild
          path: ./backend/api-gateway
          ignore:
            - ./backend/api-gateway/tmp/
            - ./backend/api-gateway/*.log

  ws:
    build:
      context: ./backend/ws-service
      dockerfile: Dockerfile
      args:
        ENV: ${ENV:-development}
    depends_on:
      redis:
        condition: service_healthy
    env_file:
    - ./backend/ws-service/.env
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/MindSyncr?sslmode=disable
    ports:
      - "3001:3001"
    develop:
      watch:
        - action: rebuild
          path: ./backend/ws-service/go.mod
        
        - action: rebuild
          path: ./backend/ws-service/go.sum
        
        - action: rebuild
          path: ./backend/ws-service
          ignore:
            - ./backend/ws-service/tmp/
            - ./backend/ws-service/*.log

volumes:
  db_data:
  redis_data:
